name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnite/setup-gyro@v1
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - run: gyro build test
